#
# Copyright 2022 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Publish Release

on:
  workflow_call:
    secrets:
      accessToken:
        required: true
      publishToken:
        required: true
      marketplaceChannel:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:


  # Prepare and publish the plugin to the Marketplace repository
  publish:
    name: Publish Plugin in Marketplace
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.tag_name }}

      # Publish the plugin to the Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.publishToken }}
          MARKETPLACE_CHANNEL: ${{ secrets.marketplaceChannel }}
        run: |
          TAG=${{ github.event.client_payload.tag_name }}
          TAG="${TAG//v/""}"
          ./gradlew publishPlugin -Dproject_version=$TAG

      # Upload artifact as a release asset
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.accessToken }}
        run: |
          gh release upload ${{ github.event.client_payload.tag_name }} ./build/distributions/*
