#
# Copyright 2022 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Publish Release

on:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true
      PUBLISH_TOKEN:
        required: true
      CHANNEL:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  EXPORT_PROPERTIES:
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.properties.outputs.changelog }}
    steps:
      # Set environment variables
      - name: Export Properties
        id: properties
        run: |
          CHANGELOG="$(cat << 'EOM' | sed -e "/## What's Changed/d" -e 's/^[[:space:]]*$//g' -e '/./,$!d'
          ${{ github.event.release.body }}
          EOM
          )"

          CHANGELOG="${CHANGELOG//'%'/'%25'}"
          CHANGELOG="${CHANGELOG//$'\n'/'%0A'}"
          CHANGELOG="${CHANGELOG//$'\r'/'%0D'}"
          CHANGELOG="${CHANGELOG//'**Full Changelog**'/'Full Changelog'}"

          echo "::set-output name=changelog::$CHANGELOG"

  # Prepare and publish the plugin to the Marketplace repository
  PUBLISH:
    name: Publish Plugin
    runs-on: ubuntu-latest
    steps:

      # Check out current repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # Publish the plugin to the Marketplace
      - name: Publish Plugin
        env:
          PUBLISH_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
          CHANNEL: ${{ secrets.CHANNEL }}
        run: |
          TAG=${{ github.event.release.tag_name }}
          TAG="${TAG//v/""}"
          ./gradlew publishPlugin -Dproject_version=$TAG

      # Upload artifact as a release asset
      - name: Upload Release Asset
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} ./build/distributions/*

  CHANGELOG:
    needs:
      - EXPORT_PROPERTIES
    runs-on: ubuntu-latest
    steps:
      # Check out current repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.release.tag_name }}

      # Update Unreleased section with the current release note
      - name: Patch Changelog
        if: ${{ needs.EXPORT_PROPERTIES.outputs.changelog != '' }}
        env:
          CHANGELOG: ${{ needs.EXPORT_PROPERTIES.outputs.changelog }}
        run: |
          ./gradlew patchChangelog --release-note="$CHANGELOG"

      # Create pull request
      - name: Create Pull Request
        if: ${{ needs.EXPORT_PROPERTIES.outputs.changelog != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          BRANCH="changelog-update-$VERSION"
          
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          
          git checkout -b $BRANCH
          git commit -asm "Changelog update - $VERSION"
          git push --set-upstream origin $BRANCH
          
          gh pr create \
            --title "Changelog update - \`$VERSION\`" \
            --body "current pull request contains patched \`changelog.md\` file for the \`$version\` version." \
            --base "${{ github.event.release.target_commitish }}" \
            --head $BRANCH \
            --label ignore-for-release
